### ISSUE TITLE
Hidden (closed) items still part of the DOM

### ISSUE THREAD

**Issue by kalinchernev** [glennflanagan/react-collapsible#250]
**Describe the bug**

`Collapsible__contentInner` elements remain in the DOM and render as big white places.

**To Reproduce**

No special steps to reproduce. Default setup.

**Expected behavior**
Please see the next screenshots.

**Screenshots**

Screenshot of the problem:

![Screenshot from 2023-03-14 12-09-56](https://user-images.githubusercontent.com/1923476/224983981-5e7abc4b-090b-4827-b2cf-8539f15e0edb.png)

Screenshot of a potential solution:

![Screenshot from 2023-03-14 12-10-15](https://user-images.githubusercontent.com/1923476/224984026-806b9b2b-e10e-4b86-868f-85b20c726d39.png)

**Additional context**

Because the styles for open/closed states in injected as inline, `Collapsible__contentOuter` level element not receiving open/closed state as a BEM modifier, a feasible CSS fix would be 

```css
.Collapsible__trigger.is-closed ~ .Collapsible__contentOuter {
  clip: rect(1px, 1px, 1px, 1px);
  height: 1px;
  overflow: hidden;
  position: absolute;
  width: 1px;
}
````

Where the `absolute` positioning is what makes the difference.
